langauge: go

go:
    - 1.3
    - 1.4

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v -d ./...
  - export PATH=$PATH:$HOME/gopath/bin

script: make test

notifications:
    email:
        on_success: change
        on_failure: always
